package com.lansitec.dao.beans;

import com.lansitec.enumlist.Alarmtype;

// Generated 2017-6-3 9:35:20 by Hibernate Tools 5.2.0.CR1

/**
 * Beacons generated by hbm2java
 */
public class Beacons implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String sn;
	private String alias;
	private String mapid;
	private float x;
	private float y;
	private byte rssi1;
	private byte rssi2;
	private float a;
	private float n;
    private Alarmtype alarmtype;
    public Beacons(){
    	
    }
    public Beacons(String sn,String alias,String mapid,float x,float y,byte rssi1,byte rssi2,float a,float n,Alarmtype alarmtype){
    	this.sn = sn;
    	this.alias = alias;
    	this.mapid = mapid;
    	this.x = x;
    	this.y = y;
    	this.rssi1 = rssi1;
    	this.rssi2 = rssi2;
    	this.a = a;
    	this.n = n;
    	this.alarmtype = alarmtype;
    }
	public Integer getId() {
		return id;
	}
	public String getSn() {
		return sn;
	}
	public String getAlias() {
		return alias;
	}
	public String getMapid() {
		return mapid;
	}
	public float getX() {
		return x;
	}
	public float getY() {
		return y;
	}
	public byte getRssi1() {
		return rssi1;
	}
	public byte getRssi2() {
		return rssi2;
	}
	public float getA() {
		return a;
	}
	public float getN() {
		return n;
	}
	public Alarmtype getAlarmtype() {
		return alarmtype;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public void setSn(String sn) {
		this.sn = sn;
	}
	public void setAlias(String alias) {
		this.alias = alias;
	}
	public void setMapid(String mapid) {
		this.mapid = mapid;
	}
	public void setX(float x) {
		this.x = x;
	}
	public void setY(float y) {
		this.y = y;
	}
	public void setRssi1(byte rssi1) {
		this.rssi1 = rssi1;
	}
	public void setRssi2(byte rssi2) {
		this.rssi2 = rssi2;
	}
	public void setA(float a) {
		this.a = a;
	}
	public void setN(float n) {
		this.n = n;
	}
	public void setAlarmtype(Alarmtype alarmtype) {
		this.alarmtype = alarmtype;
	}
}
