package com.lans.dao.beans;
// Generated 2017-6-3 9:35:20 by Hibernate Tools 5.2.0.CR1

/**
 * Beacons generated by hbm2java
 */
public class Beacons implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int major;
	private int minor;
	private String flor;
	private String postype;
	private String owner;
	private String description;
	private double lati;
	private double longi;
	private double x;
	private double y;
	private byte rssi1;
	private byte rssi2;
	private double a;
	private double n;

	public Beacons() {
	}

	public Beacons(int major, int minor, String flor, String postype, String owner, String description, double lati,
			double longi, double x, double y, byte rssi1, byte rssi2, double a, double n) {
		this.major = major;
		this.minor = minor;
		this.flor = flor;
		this.postype = postype;
		this.owner = owner;
		this.description = description;
		this.lati = lati;
		this.longi = longi;
		this.x = x;
		this.y = y;
		this.rssi1 = rssi1;
		this.rssi2 = rssi2;
		this.a = a;
		this.n = n;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMajor() {
		return this.major;
	}

	public void setMajor(int major) {
		this.major = major;
	}

	public int getMinor() {
		return this.minor;
	}

	public void setMinor(int minor) {
		this.minor = minor;
	}

	public String getFlor() {
		return this.flor;
	}

	public void setFlor(String flor) {
		this.flor = flor;
	}

	public String getPostype() {
		return this.postype;
	}

	public void setPostype(String postype) {
		this.postype = postype;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getLati() {
		return this.lati;
	}

	public void setLati(double lati) {
		this.lati = lati;
	}

	public double getLongi() {
		return this.longi;
	}

	public void setLongi(double longi) {
		this.longi = longi;
	}

	public double getX() {
		return this.x;
	}

	public void setX(double x) {
		this.x = x;
	}

	public double getY() {
		return this.y;
	}

	public void setY(double y) {
		this.y = y;
	}

	public byte getRssi1() {
		return this.rssi1;
	}

	public void setRssi1(byte rssi1) {
		this.rssi1 = rssi1;
	}

	public byte getRssi2() {
		return this.rssi2;
	}

	public void setRssi2(byte rssi2) {
		this.rssi2 = rssi2;
	}

	public double getA() {
		return this.a;
	}

	public void setA(double a) {
		this.a = a;
	}

	public double getN() {
		return this.n;
	}

	public void setN(double n) {
		this.n = n;
	}

}
