package com.lans.dao.beans;
//Generated 2017-6-3 9:35:20 by Hibernate Tools 5.2.0.CR1

/**
* DevConfig generated by hbm2java
*/
public class DevConfig implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String deveui;
	private byte ADR ;
	private byte RFU;
	private byte DR;
	private byte MODE;
	private byte S_MODE;
	private byte POWER;
	private byte LOSTPOINT;
	private byte SELFADAPT;
	private byte ONEOFF;
	private byte ALREPORT;
	private short GPS;
	private short HB;
	private short CRC16;
	
	public DevConfig(){
		
	}
	
    public DevConfig(String deveui,byte ADR ,byte RFU,byte DR,byte MODE,byte S_MODE,byte POWER,
    		byte LOSTPOINT,byte SELFADAPT,byte ONEOFF,byte ALREPORT, short GPS,short HB,short CRC16){
    	this.deveui = deveui;
    	this.ADR = ADR;
    	this.RFU = RFU;
    	this.DR = DR;
    	this.MODE = MODE;
    	this.S_MODE = S_MODE;
    	this.POWER = POWER;
    	this.LOSTPOINT = LOSTPOINT;
    	this.SELFADAPT = SELFADAPT;
    	this.ONEOFF = ONEOFF;
    	this.ALREPORT = ALREPORT;
    	this.GPS = GPS;
    	this.HB = HB;
    	this.CRC16 = CRC16;
		
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDeveui() {
		return deveui;
	}

	public void setDeveui(String deveui) {
		this.deveui = deveui;
	}

	public byte getADR() {
		return ADR;
	}

	public void setADR(byte aDR) {
		ADR = aDR;
	}

	public byte getRFU() {
		return RFU;
	}

	public void setRFU(byte rFU) {
		RFU = rFU;
	}

	public byte getDR() {
		return DR;
	}

	public void setDR(byte dR) {
		DR = dR;
	}

	public byte getMODE() {
		return MODE;
	}

	public void setMODE(byte mODE) {
		MODE = mODE;
	}

	public byte getS_MODE() {
		return S_MODE;
	}

	public void setS_MODE(byte s_MODE) {
		S_MODE = s_MODE;
	}

	public byte getPOWER() {
		return POWER;
	}

	public void setPOWER(byte pOWER) {
		POWER = pOWER;
	}

	public byte getLOSTPOINT() {
		return LOSTPOINT;
	}

	public void setLOSTPOINT(byte lOSTPOINT) {
		LOSTPOINT = lOSTPOINT;
	}

	public byte getSELFADAPT() {
		return SELFADAPT;
	}

	public void setSELFADAPT(byte sELFADAPT) {
		SELFADAPT = sELFADAPT;
	}

	public byte getONEOFF() {
		return ONEOFF;
	}

	public void setONEOFF(byte oNEOFF) {
		ONEOFF = oNEOFF;
	}

	public byte getALREPORT() {
		return ALREPORT;
	}

	public void setALREPORT(byte aLREPORT) {
		ALREPORT = aLREPORT;
	}

	public short getGPS() {
		return GPS;
	}

	public void setGPS(short gPS) {
		GPS = gPS;
	}

	public short getHB() {
		return HB;
	}

	public void setHB(short hB) {
		HB = hB;
	}

	public short getCRC16() {
		return CRC16;
	}

	public void setCRC16(short cRC16) {
		CRC16 = cRC16;
	}
}
