package com.lans.dao.beans;
// Generated 2017-6-3 9:35:20 by Hibernate Tools 5.2.0.CR1

/**
 * Zwwldevices generated by hbm2java
 */
public class Zwwldevices implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String devid;
	private String cfgtype;
	private int movthr;
    private String status;
    private int energycyclevalue;
    private int lowbatterythr;
    private int stepscyclevalue;
    private String gateway;
    private String tenantId;
    private String devType;
	public Zwwldevices() {
		
	}

	public Zwwldevices(String devid, String cfgtype, int movthr,String status,int energycyclevalue,int lowbatterythr,int stepscyclevalue,String gateway,String tenantId,String devType) {
		this.devid = devid;
		this.cfgtype = cfgtype;
		this.movthr = movthr;
		this.status = status;
		this.energycyclevalue = energycyclevalue;
		this.lowbatterythr = lowbatterythr;
		this.stepscyclevalue = stepscyclevalue;
		this.gateway = gateway;
		this.tenantId = tenantId;
		this.devType = devType;
	}

	public Integer getId() {
		return id;
	}

	public String getDevid() {
		return devid;
	}

	public String getCfgtype() {
		return cfgtype;
	}

	public int getMovthr() {
		return movthr;
	}

	public String getStatus() {
		return status;
	}

	public int getEnergycyclevalue() {
		return energycyclevalue;
	}

	public int getLowbatterythr() {
		return lowbatterythr;
	}

	public int getStepscyclevalue() {
		return stepscyclevalue;
	}

	public String getGateway() {
		return gateway;
	}

	public String getTenantId() {
		return tenantId;
	}

	public String getDevType() {
		return devType;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setDevid(String devid) {
		this.devid = devid;
	}

	public void setCfgtype(String cfgtype) {
		this.cfgtype = cfgtype;
	}

	public void setMovthr(int movthr) {
		this.movthr = movthr;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setEnergycyclevalue(int energycyclevalue) {
		this.energycyclevalue = energycyclevalue;
	}

	public void setLowbatterythr(int lowbatterythr) {
		this.lowbatterythr = lowbatterythr;
	}

	public void setStepscyclevalue(int stepscyclevalue) {
		this.stepscyclevalue = stepscyclevalue;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public void setDevType(String devType) {
		this.devType = devType;
	}

}
