package com.lansitec.enumlist;

public enum ReqProcRsltType {
	SUCC_RESP_STR,
	SUCC_RESP_OBJ,
	SUCC_NO_RESP,
	FAIL_RESP_STR,
	ERROR_RESP_OBJ,
	FAIL_NO_RESP,
	NOTADD_NO_RESP,
	NOEXIST_NO_RESP,
	COPYADD_NO_RESP
}
